version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  auth:
    build: ./auth
    container_name: auth
    restart: unless-stopped
    ports:
      - "${AUTH_SERVICE_PORT}:8000"
    environment:
      SERVER_PORT: 8000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_SSLMODE: disable
      JWT_SECRET: ${AUTH_SERVICE_JWT_SECRET}
    depends_on:
      - postgres
    networks:
      - backend

  user:
    build: ./user
    container_name: user
    restart: unless-stopped
    ports:
      - "${USER_SERVICE_PORT}:8000"
    environment:
      SERVER_PORT: 8000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_SSLMODE: disable
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge
